name: Saving blobs
 
on: push

env:
  TZ: Europe/London
  ECID: 59973168996   # Write in decimal format
  BOARDCONFIG: N53AP  # Can be obtained with iTunes, 3utools or TSSSaver's app
  DEVICEID: iPhone6,2 # Can be obtained with iTunes, 3utools or TSSSaver's app
  
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        name: Requesting from TSSSaver
        run: |
            curl -X POST -d '{"ecid": "'"$ECID"'", "boardConfig": "'"$BOARDCONFIG"'", "deviceIdentifier": "'"$DEVICEID"'"}' -v -i 'https://tsssaver.1conan.com/v2/api/save.php'
