name: Saving blobs
 
on:
 push:
 
 schedule:
  - cron: '0 0,12 * * *

env:
  TZ: Europe/London
  ECID: 59973168996   # Write in decimal format
  BOARDCONFIG: N53AP  # Can be obtained with iTunes, 3utools or TSSSaver's app
  DEVICEID: iPhone6,2 # Can be obtained with iTunes, 3utools or TSSSaver's app
  APNONCE: 3a88b7c3802f2f0510abc432104a15ebd8bd7154 # Can be grabbed from last section of pre-existing blob, or a jailbroken device in recovery mode and libimobiledevice. See commit 693e37b for some known nonces for A11 and below
  
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        name: Requesting from TSSSaver
        run: |
            curl -X POST -d '{"ecid": "'"$ECID"'", "boardConfig": "'"$BOARDCONFIG"'", "deviceIdentifier": "'"$DEVICEID"'", "apnonce": "'"$APNONCE"'"}' -v -i 'https://tsssaver.1conan.com/v2/api/save.php'
